/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ClerkWebhook': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ListPrompts': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreatePrompt': ApiRouteHandler<{ content: string }, ApiResponse<201, { id: string; userId: string; content: string; createdAt: string; updatedAt: string }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, never>
  }
    
}